core/accounts/api/v1/urls.py
from django.urls import path
from rest_framework_simplejwt.views import TokenRefreshView, TokenVerifyView
from . import views

app_name = "api-v1"

urlpatterns = [
    path(
        "registration/", views.RegistrationView.as_view(), name="registration"
    ),
    path("token/login/", views.LoginView.as_view(), name="login"),
    path("token/logout/", views.LogoutView.as_view(), name="logout"),
    path(
        "jwt/create/",
        views.CustomTokenObtainPairView.as_view(),
        name="jwt-create",
    ),
    path("jwt/refresh/", TokenRefreshView.as_view(), name="jwt-refresh"),
    path("jwt/verify/", TokenVerifyView.as_view(), name="token_verify"),
    path(
        "email/confirm/<str:token>/",
        views.EmailConfirmView.as_view(),
        name="email-confirm",
    ),
    path(
        "email/resend/confirm/",
        views.EmailResendConfirmView.as_view(),
        name="email-resend-confirm",
    ),
    path(
        "change-password/",
        views.ChangePasswordView.as_view(),
        name="change-password",
    ),
    path("profile/", views.ProfileView.as_view(), name="profile"),
]

core/accounts/urls.py
from django.urls import path, include
from .views import *

app_name = "accounts"

urlpatterns = [
    path("api/v1/", include("accounts.api.v1.urls"), name="api-v1"),
    path("login/", SignInView.as_view(), name="sign_in"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("sign_up/", SignUpView.as_view(), name="sign_up"),
]

core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views
from todo.api.v1 import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

"""
This function initializes and configures the schema view for the API documentation.

Parameters:
- openapi.Info: Contains information about the API, such as title, version, description, terms of service, contact details, and license.
- public (bool): Indicates whether the API documentation is publicly accessible.
- permission_classes (tuple): Specifies the permission classes required to access the API documentation.

Returns:
- schema_view: An instance of the get_schema_view function, configured with the provided parameters.
"""
schema_view = get_schema_view(
    openapi.Info(
        title="Task API",
        default_version="v1",
        description="This page is for the documentation task",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.DefaultPermission,),
)
urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("todo.urls")),
    path("api-auth", include("rest_framework.urls")),
    path("accounts/", include("accounts.urls")),
    path("captcha/", include("captcha.urls")),
    path(
        "swagger/output.json",
        schema_view.without_ui(cache_timeout=0),
        name="schema-json",
    ),
    path(
        "swagger/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path(
        "redoc/",
        schema_view.with_ui("redoc", cache_timeout=0),
        name="schema-redoc",
    ),
]

urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

core/accounts/forms.py
from django import forms
from captcha.fields import CaptchaField


class SignUpForm(forms.Form):
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput)
    confirm_password = forms.CharField(widget=forms.PasswordInput)
    captcha = CaptchaField()


class SignInForm(forms.Form):
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput)
    captcha = CaptchaField()


core/accounts/api/v1/views.py
from rest_framework_simplejwt.tokens import RefreshToken
from mail_templated import EmailMessage 
from rest_framework import generics, status, serializers
from rest_framework.permissions import AllowAny, IsAuthenticated
from rest_framework.response import Response
from django.urls import reverse
from django.conf import settings
from rest_framework.views import APIView
import jwt
from django.contrib.auth import get_user_model
from rest_framework.authtoken.models import Token 
from django.contrib.auth import authenticate
from rest_framework_simplejwt.views import TokenObtainPairView
from ..utils import EmailThread
from .serializers import (
    RegistrationSerializer,
    ResendEmailConfirmSerializer,
    ChangePasswordSerializer,
    ProfileSerializer,
    LoginSerializer,
    CustomTokenObtainPairSerializer,
)
from accounts.models import Profile


class RegistrationView(generics.GenericAPIView):
    """
    This API endpoint allows users to register a new account. Upon successful registration, an email confirmation link is sent to the user's email address.

    Args:
        request (HttpRequest): The HTTP request object containing the user's registration data.

    Returns:
        Response: A JSON response containing a message indicating whether the registration was successful or if there were any errors.

    Raises:
        ValidationError: If the provided registration data is invalid.
    """

    serializer_class = RegistrationSerializer
    permission_classes = [AllowAny]

    def post(self, request, *args, **kwargs):
        serializer = self.serializer_class(data=request.data)

        if serializer.is_valid():
            user = serializer.save()
            email = serializer.validated_data["email"]
            data = {
                "details": f"account {email} created. pleas check your email for verify account"
            }

            token = self.get_tokens_for_user(user)

            from_email = "your_email@example.com"
            recipient_list = [email]
            url = request.build_absolute_uri(
                reverse("accounts:api-v1:email-confirm", args=[token])
            )

            email_obj = EmailMessage(
                "email/send-mail-confirm.tpl",
                {"url": url},
                from_email,
                to=recipient_list,
            )

            EmailThread(email_obj).start()

            return Response(data, status=status.HTTP_201_CREATED)

        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def get_tokens_for_user(self, user):
        refresh = RefreshToken.for_user(user)
        return str(refresh.access_token)


User = get_user_model()


class EmailConfirmView(APIView):
    """
    This API endpoint allows users to confirm their email address by providing the email confirmation token.

    Args:
        request (HttpRequest): The HTTP request object containing the user's email confirmation token.

    Returns:
        Response: A JSON response containing a message indicating whether the email address was successfully confirmed or if there were any errors.

    Raises:
        ValidationError: If the provided email confirmation token is invalid.
    """

    def get(self, request, token, *args, **kwargs):
        try:
            decoded = jwt.decode(
                token, settings.SECRET_KEY, algorithms=["HS256"]
            )
        except jwt.ExpiredSignatureError:
            return Response(
                {"detail": "This token is expired."},
                status=status.HTTP_400_BAD_REQUEST,
            )
        except jwt.InvalidTokenError:

            return Response(
                {"detail": "This token is invalid."},
                status=status.HTTP_400_BAD_REQUEST,
            )

        user_id = decoded.get("user_id")

        try:
            user = User.objects.get(id=user_id)
            user.is_verified = True
            user.save()
            return Response(
                {"detail": "Account verified."}, status=status.HTTP_200_OK
            )
        except User.DoesNotExist:
            return Response(
                {"detail": "User not found."}, status=status.HTTP_404_NOT_FOUND
            )


class EmailResendConfirmView(generics.GenericAPIView):
    """
    This API endpoint allows users to resend the email confirmation link.

    Args:
        request (HttpRequest): The HTTP request object containing the user's email address and token.

    Returns:
        Response: A JSON response containing a message indicating whether the email confirmation link was successfully resend or if there were any errors.

    Raises:
        ValidationError: If the provided email address or token is invalid.
    """

    serializer_class = ResendEmailConfirmSerializer
    permission_classes = [AllowAny]

    def post(self, request, *args, **kwargs):
        serializer = self.serializer_class(data=request.data)
        serializer.is_valid(raise_exception=True)
        email = serializer.validated_data["email"]
        user = serializer.validated_data["user"]

        token = self.get_tokens_for_user(user)
        from_email = "your_email@example.com"
        recipient_list = [email]
        url = request.build_absolute_uri(
            reverse("accounts:api-v1:email-confirm", args=[token])
        )

        email_obj = EmailMessage(
            "email/resend-mail-confirm.tpl",
            {"url": url},
            from_email,
            to=recipient_list,
        )

        EmailThread(email_obj).start()

        return Response({"detail": "Pleas check your email"})

    def get_tokens_for_user(self, user):
        refresh = RefreshToken.for_user(user)
        return str(refresh.access_token)


class ChangePasswordView(generics.UpdateAPIView):
    """
    This API endpoint allows users to change their password.

    Args:
        request (HttpRequest): The HTTP request object containing the user's new password.

    Returns:
        Response: A JSON response containing a message indicating whether the password was successfully changed or if there were any errors.

    Raises:
        AuthenticationFailed: If the provided credentials are invalid.
    """

    queryset = User.objects.all()
    serializer_class = ChangePasswordSerializer
    permission_classes = [IsAuthenticated]

    def get_object(self):
        return self.request.user

    def update(self, request, *args, **kwargs):
        self.object = self.get_object()
        serializer = self.get_serializer(self.object, data=request.data)

        serializer.is_valid(raise_exception=True)

        self.object.set_password(serializer.validated_data["new_password"])
        self.object.save()

        return Response(
            {"detail": "Password updated successfully!"},
            status=status.HTTP_200_OK,
        )


class ProfileView(generics.RetrieveUpdateAPIView):
    """
    This API endpoint allows users to retrieve and update their profile information.

    Args:
        request (HttpRequest): The HTTP request object containing the user's profile data.

    Returns:
        Response: A JSON response containing the user's profile information or a message indicating whether the profile was successfully updated or if there were any errors.

    Raises:
        AuthenticationFailed: If the provided credentials are invalid.
    """

    serializer_class = ProfileSerializer
    queryset = Profile.objects.all()
    permission_classes = [IsAuthenticated]

    def get_object(self):
        return self.queryset.get(user=self.request.user.id)


class LoginView(generics.GenericAPIView):
    """
    Allows users to log in by providing their username and password.

    Upon successful validation, the view returns a JSON response containing the user's authentication token and email.

    Args:
        request (HttpRequest): The HTTP request object containing the user's login credentials.

    Returns:
        Response: A JSON response containing the user's authentication token and email.

    Raises:
        AuthenticationFailed: If the provided credentials are invalid.
    """

    serializer_class = LoginSerializer
    permission_classes = [AllowAny]

    def post(self, request):
        serializer = self.serializer_class(data=request.data)
        serializer.is_valid(raise_exception=True)
        user = serializer.validated_data["user"]
        token, created = Token.objects.get_or_create(user=user)
        return Response({"token": token.key, "email": user.email})


class LogoutView(APIView):
    """
    Logs out the user by deleting their authentication token.

    Args:
        request (HttpRequest): The HTTP request object containing the user's authentication token.

    Returns:
        Response: A JSON response containing a message indicating whether the logout was successful or if the token does not exist.

    Raises:
        AttributeError: If the user does not have an 'auth_token' attribute.
        Token.DoesNotExist: If the user's authentication token does not exist.
    """

    permission_classes = [IsAuthenticated]

    def post(self, request):
        try:
            request.user.auth_token.delete()
            return Response({"detail": "Successfully logged out."}, status=200)
        except (AttributeError, Token.DoesNotExist):
            return Response({"detail": "Token does not exist."}, status=400)


class CustomTokenObtainPairView(TokenObtainPairView):
    """
    Custom implementation of TokenObtainPairView for obtaining JWT tokens.

    This view allows users to obtain a JWT token pair by providing their username and password.

    Args:
        TokenObtainPairView (class): The base class for obtaining JWT token pair.
        serializer_class (class): A custom serializer class for handling token generation.

    Returns:
        A JSON response containing the access and refresh tokens.
    """

    serializer_class = CustomTokenObtainPairSerializer

core/accounts/views.py
from django.urls import reverse_lazy
from django.views.generic import FormView
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from .forms import SignInForm, SignUpForm
from django.shortcuts import redirect
from django.http import HttpResponse
from time import sleep 

User = get_user_model()

from .forms import SignInForm


class SignInView(FormView):
    template_name = "accounts/sign_in.html"
    form_class = SignInForm
    success_url = reverse_lazy("todo:list_task")

    def form_valid(self, form):
        email = form.cleaned_data["email"]
        password = form.cleaned_data["password"]
        email = str(email)

        user = authenticate(request=self.request, email=email, password=password)

        if user is not None:
            login(self.request, user)
            return super().form_valid(form)
        else:  # Correctly using "else"
            messages.error(self.request, "This user does not exist.")
            return self.form_invalid(form)

    def form_invalid(self, form):
        messages.error(self.request, "The entered captcha does not match.")
        return super().form_invalid(form)


class SignUpView(FormView):
    template_name = "accounts/sign_up.html"
    form_class = SignUpForm
    success_url = reverse_lazy("accounts:sign_in")

    def form_valid(self, form):
        email = form.cleaned_data["email"]
        password = form.cleaned_data["password"]
        confirm_password = form.cleaned_data["confirm_password"]

        if not User.objects.filter(email=email).exists():
            if password == confirm_password:
                User.objects.create_user(email=email, password=password)
                return super().form_valid(form)
            else:
                messages.error(
                    self.request,
                    "New password and confirm password do not match.",
                )
        else:
            messages.error(self.request, "This username already exists.")


class LogoutView(LoginRequiredMixin, FormView):
    def get(self, request, *args, **kwargs):
        logout(request)
        return redirect("accounts:sign_in")


core/templates/accounts/sign_in.html
{% load static %}
<!DOCTYPE html>
<!-- Coding By CodingNepal - codingnepalweb.com -->
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> Responsive Login</title>

    <!-- CSS -->
    <link rel="stylesheet" href="{% static 'css/login/style.css' %}">

    <!-- Boxicons CSS -->
    <link href='https://unpkg.com/boxicons@2.1.2/css/boxicons.min.css' rel='stylesheet'>

</head>

<body>
    <section class="container forms">
        <div class="form login">
            <div class="form-content">
                <header>Login</header>
                <form method="post" action="#">
                    {% csrf_token %}
                    <div class="field input-field">
                        <input name="email" type="email" placeholder="Email" class="input">
                    </div>

                    <div class="field input-field">
                        <input name="password" type="password" placeholder="Password" class="password">
                        <i class='bx bx-hide eye-icon'></i>
                    </div>
                    <div class="field input-field">
                        {{ form.captcha }}
                    </div><br>

                    <div class="field button-field">
                        <button type="submit">Login</button>
                    </div>
                </form>

                <div class="form-link">
                    <span>Don't have an account? <a href="{% url 'accounts:sign_up' %}">Signup</a></span>
                </div>
                {% if messages %}
                <script>
                    {% for message in messages %}
                    alert("{{ message|escapejs }}");
                    {% endfor %}
                </script>
                {% endif %}
            </div>
        </div>


    </section>

    <!-- JavaScript -->
    <script src="{% static 'js/script.js' %}"></script>
</body>

</html>

core/templates/accounts/sign_up.html
{% load static %}
<!DOCTYPE html>
<!-- Coding By CodingNepal - codingnepalweb.com -->
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> Responsive Signup Form </title>

    <!-- CSS -->
    <link rel="stylesheet" href="{% static 'css/login/style.css' %}">

    <!-- Boxicons CSS -->
    <link href='https://unpkg.com/boxicons@2.1.2/css/boxicons.min.css' rel='stylesheet'>

</head>

<body>
    <section class="container forms">

        <!-- Signup Form -->
        <div class="form login">
            <div class="form-content">
                <header>Signup</header>
                <form method="post" action="#">
                    {% csrf_token %}
                    <div class="field input-field">
                        <input name="email" type="email" placeholder="Email" class="input">
                    </div>

                    <div class="field input-field">
                        <input name="password" type="password" placeholder="Create password" class="password">
                    </div>

                    <div class="field input-field">
                        <input name="confirm_password" type="password" placeholder="Confirm password" class="password">
                        <i class='bx bx-hide eye-icon'></i>
                    </div>
                    
                    <div class="field input-field">
                        {{ form.captcha }}
                    </div><br>
                    
                    <div class="field button-field">
                        <button type="submit">Sign up</button>
                    </div>
                </form>

                <div class="form-link">
                    <span>Already have an account? <a href="{% url 'accounts:sign_in' %}" >Login</a></span>
                </div>
                {% if messages %}
                <script>
                    {% for message in messages %}
                    alert("{{ message|escapejs }}");
                    {% endfor %}
                </script>
                {% endif %}
            </div>
            


        </div>
    </section>

    <!-- JavaScript -->
    <script src="{% static 'js/script.js' %}"></script>
</body>

</html>