core/accounts/urls.py
from django.urls import path, include
from .views import *

app_name = "accounts"

urlpatterns = [
    path("api/v1/", include("accounts.api.v1.urls"), name="api-v1"),
    path("login/", SignInView.as_view(), name="sign_in"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("sign_up/", SignUpView.as_view(), name="sign_up"),
]

core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views
from todo.api.v1 import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

"""
This function initializes and configures the schema view for the API documentation.

Parameters:
- openapi.Info: Contains information about the API, such as title, version, description, terms of service, contact details, and license.
- public (bool): Indicates whether the API documentation is publicly accessible.
- permission_classes (tuple): Specifies the permission classes required to access the API documentation.

Returns:
- schema_view: An instance of the get_schema_view function, configured with the provided parameters.
"""
schema_view = get_schema_view(
    openapi.Info(
        title="Task API",
        default_version="v1",
        description="This page is for the documentation task",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.DefaultPermission,),
)
urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("todo.urls")),
    path("api-auth", include("rest_framework.urls")),
    path("accounts/", include("accounts.urls")),
    path("captcha/", include("captcha.urls")),
    path(
        "swagger/output.json",
        schema_view.without_ui(cache_timeout=0),
        name="schema-json",
    ),
    path(
        "swagger/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path(
        "redoc/",
        schema_view.with_ui("redoc", cache_timeout=0),
        name="schema-redoc",
    ),
]

urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

core/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Todo Application</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
    <header>
        <h1>Task Management</h1>
        <nav>
            <ul>
                <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
            </ul>
        </nav>
    </header>
    {% block main %} {% endblock %}

    <footer>
        <p>© 2024 Todo App. All rights reserved.</p>
    </footer>
</body>
</html>