core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views
from todo.api.v1 import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

"""
This function initializes and configures the schema view for the API documentation.

Parameters:
- openapi.Info: Contains information about the API, such as title, version, description, terms of service, contact details, and license.
- public (bool): Indicates whether the API documentation is publicly accessible.
- permission_classes (tuple): Specifies the permission classes required to access the API documentation.

Returns:
- schema_view: An instance of the get_schema_view function, configured with the provided parameters.
"""
schema_view = get_schema_view(
    openapi.Info(
        title="Task API",
        default_version="v1",
        description="This page is for the documentation task",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.DefaultPermission,),
)
urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("todo.urls")),
    path("api-auth", include("rest_framework.urls")),
    path("accounts/", include("accounts.urls")),
    path("captcha/", include("captcha.urls")),
    path(
        "swagger/output.json",
        schema_view.without_ui(cache_timeout=0),
        name="schema-json",
    ),
    path(
        "swagger/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path(
        "redoc/",
        schema_view.with_ui("redoc", cache_timeout=0),
        name="schema-redoc",
    ),
]

urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

core/todo/api/v1/urls.py
from django.urls import path
from rest_framework.routers import DefaultRouter
from .views import TaskViewSet, WeatherAPIView
"""
This module contains the URL configuration for the API v1 of the ToDo application.

The `router` is an instance of `DefaultRouter` from the `rest_framework.routers` module.
It is used to automatically generate the URL patterns for the registered viewsets.

The `TaskViewSet` is a custom viewset defined in the `views.py` module.
It is responsible for handling CRUD operations for the Task model.

The `urlpatterns` variable is a list of URL patterns generated by the `router`.
These patterns are used to map URLs to the corresponding viewsets.

The `app_name` variable is used to namespace the URLs within the ToDo application.
"""

from django.views.decorators.cache import cache_page


app_name = "api-v1"

router = DefaultRouter()
router.register("task", TaskViewSet, basename="task")
urlpatterns = router.urls
urlpatterns += [
    path('api/weather/<str:city_name>/', WeatherAPIView.as_view(), name='weather'),

]

core/todo/urls.py
from django.urls import path, include
from django.views.decorators.cache import cache_page
from .views import *

app_name = "todo"

urlpatterns = [
    path("",TaskListView.as_view(), name="list_task"),
    path("create/", TaskCreateView.as_view(), name="create_task"),
    path("delete/<int:pk>/", TaskDeleteView.as_view(), name="delete_task"),
    path("edit/<int:pk>/", TaskUpdateView.as_view(), name="edit_task"),
    path(
        "toggle_task/<int:pk>/",
        ToggleTaskUpdateView.as_view(),
        name="toggle_task",
    ),
    path("api/v1/", include("todo.api.v1.urls"), name="api-v1"),
]

core/todo/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse


class Task(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    title = models.CharField(max_length=225)
    is_done = models.BooleanField(default=False)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return reverse("todo:api-v1:task-detail", kwargs={"pk": self.pk})

core/todo/forms.py
from django import forms
from .models import Task


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = [
            "title",
        ]

core/todo/api/v1/views.py
from rest_framework import viewsets
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework.filters import SearchFilter, OrderingFilter
from rest_framework.permissions import IsAuthenticated
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
import redis
import requests
import json

from todo.models import Task
from .serializers import TaskSerializer
from .permissions import DefaultPermission
from .filters import TaskFilter



class TaskViewSet(viewsets.ModelViewSet):
    """
    A ViewSet for managing tasks. It uses Django REST Framework's ModelViewSet,
    which provides CRUD operations by default.

    Attributes:
    queryset: The queryset of Task objects to be used for this ViewSet.
    serializer_class: The serializer class to be used for serializing and deserializing Task objects.
    permission_classes: The list of permission classes to be applied to this ViewSet.
    filter_backends: The list of filter backends to be used for filtering tasks.
    filterset_class: The filterset class to be used for filtering tasks.
    search_fields: The list of fields to be searched when performing a search operation.
    ordering_fields: The list of fields to be used for ordering tasks.
    ordering: The default ordering of tasks.
    """

    queryset = Task.objects.all()
    serializer_class = TaskSerializer
    permission_classes = [DefaultPermission,IsAuthenticated]

    filter_backends = [DjangoFilterBackend, SearchFilter, OrderingFilter]
    filterset_class = TaskFilter
    search_fields = ["title"]
    ordering_fields = ["is_done"]
    ordering = ["-is_done"]




# Redis connection
# redis_client = redis.StrictRedis(host='redis', port=6379, db=0)

from django.utils.decorators import method_decorator
from django.views.decorators.cache import cache_page

@method_decorator(cache_page(60 * 20), name='dispatch')  
class WeatherAPIView(APIView):
    def get(self, request, city_name):

        # Fetch the weather data from an external API
        api_key = '1e7173b8a2b50e85add91dfd559f83da'
        url = f'http://api.openweathermap.org/data/2.5/weather?q={city_name}&appid={api_key}&units=metric'
        response = requests.get(url)

        if response.status_code == 200:
            weather_data = response.json()
            
            return Response(weather_data, status=status.HTTP_200_OK)
        
        return Response({'error': 'City not found'}, status=status.HTTP_404_NOT_FOUND)
    

core/todo/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import CreateView, DeleteView, ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from .models import Task
from .forms import TaskForm
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin


class TaskCreateView(LoginRequiredMixin, CreateView):
    model = Task
    fields = ["title"]
    success_url = reverse_lazy("todo:list_task")

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(TaskCreateView, self).form_valid(form)


class TaskListView(ListView, LoginRequiredMixin):
    model = Task
    template_name = "todo/main.html"
    context_object_name = "tasks"

    def get_queryset(self):
        return Task.objects.filter(user=self.request.user)

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect("accounts:sign_in")
        return super().dispatch(request, *args, **kwargs)


class TaskDeleteView(LoginRequiredMixin, DeleteView):
    model = Task
    context_object_name = "task"
    success_url = reverse_lazy("todo:list_task")

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)

    def get_queryset(self):
        return self.model.objects.filter(user=self.request.user)


class TaskUpdateView(LoginRequiredMixin, View):
    def get(self, request, pk):
        task = get_object_or_404(Task, pk=pk, user=request.user)
        form = TaskForm(instance=task)
        return render(request, "todo/edit_task.html", {"form": form})

    def post(self, request, pk):
        task = get_object_or_404(Task, pk=pk, user=request.user)
        form = TaskForm(request.POST, instance=task)
        if form.is_valid():
            form.save()
            return redirect("todo:list_task")
        return render(request, "todo/edit_task.html", {"form": form})


class ToggleTaskUpdateView(LoginRequiredMixin, View):

    def post(self, request, pk):
        task = get_object_or_404(Task, pk=pk, user=request.user)
        task.is_done = not task.is_done
        task.save()
        return redirect("todo:list_task")

core/templates/todo/edit_task.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Edit Task</title>
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
  <header>
    <h1>Task Manager</h1>
  </header>
  <div class="task-container">
    <h2>Edit Task</h2>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Save</button>
      <button onclick="location.href='{% url 'todo:list_task' %}'">Cancel</button>
    </form>

    {% if form.errors %}
      <div class="error">
        <h2>Errors:</h2>
        <ul>
          {% for field in form %}
            {% for error in field.errors %}
              <li>{{ field.label }}: {{ error }}</li>
            {% endfor %}
          {% endfor %}
          {% for error in form.non_field_errors %}
            <li>{{ error }}</li>
          {% endfor %}
        </ul>
      </div>
    {% endif %}
  </div>
  <footer>
    <p>&copy; 2023 Task Manager</p>
  </footer>
</body>
</html>

core/templates/todo/main.html
{% extends 'base.html' %}
{% load cache %} 
{% block main %}
<main>
    <section class="task-container">
        <h2>My Tasks</h2>
        <form class="pt-3" method="POST" action="{% url 'todo:create_task' %}">
            {% csrf_token %}
            <div class="input-group mb-3">
              <input type="text" class="form-control rounded-4" name="title" placeholder="Enter task title"
                aria-label="Recipient's username" aria-describedby="button-addon2">
              <button class="btn btn-primary" type="submit">Add</button>
            </div>
        </form>

        <ul id="task-list">
            {% for task in tasks %}
            
                <li class="{% if task.is_done %}done{% endif %}">
                    <span>{{ task.title }}</span>


                    <button onclick="location.href='{% url 'todo:edit_task' task.pk %}'">Edit</button>
                    <form class="pt-3" method="POST" action="{% url 'todo:delete_task' task.pk %}">
                        {% csrf_token %}
                        <button type="submit">Delete</button>
                    </form>
                    
                    <form class="pt-3" method="POST" action="{% url 'todo:toggle_task' task.pk %}">
                        {% csrf_token %}
                        <button>{% if task.is_done %}Restore{% else %}Done{% endif %}
                    </form>
                        
                </li>  
            {% endfor %}
        </ul>
    </section>
</main>
{% endblock %}